### PR TITLE
Improves error handling by using `thiserror` lib

### LINKED ISSUE #311: Use thiserror to handle errors
⚠️ Do not start contributing to this issue before this PR is merged: #297

Currently we are implementing all our errors by hand. 

Exemple: 

https://github.com/meilisearch/meilisearch-rust/blob/6f98caff09c2439002ac53307d1748a849c9e600/src/errors.rs#L58-L68

This would be way more simple using the [thiserror](https://docs.rs/thiserror/latest/thiserror/) library.

### PR DESCRIPTION
**Pull request by romilpunetha**
# Pull Request

## Related issue
Fixes #311 and #162

## What does this PR do?
- Updates `errors.rs` to use `thiserror` lib thereby simplifying how errors are managed.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by romilpunetha** [comment]
@bidoubiwa

**Review by irevoire — DISMISSED** [review]
Nice, thank you @romilpunetha

**Comment by bidoubiwa** [comment]
Hey @romilpunetha!

Thanks for your contirbution 🙏 Could you run `cargo fmt` locally? We forgot to add it in the contributing guide.
I added it in #357. Sorry for that

**Comment by romilpunetha** [comment]
> cargo fmt

Done

**Review by bidoubiwa — APPROVED** [review]
bors merge

**Comment by bidoubiwa** [comment]
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
