### PR TITLE
Update docs according to v0.25.0

### PR DESCRIPTION
**Pull request by curquiza**
- Remove `update` mention from the README
- rename `update_type` to `task_type`
- Add code samples for v0.25.0 according to https://github.com/meilisearch/documentation/pull/1288/files

### CODE REVIEW

**Comment by curquiza** [comment]
bors try

**Review by irevoire — APPROVED** [review]
lgtm thanks 👍

**Comment by curquiza** [comment]
bors mege

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
