### PR TITLE
Use _geo in examples rather then geo

### LINKED ISSUE #302: Use "_geo" in example rather then "geo"
The example on https://docs.meilisearch.com/learn/getting_started/filtering_and_sorting.html#settings uses "geo" rather than "_geo". It should use "_geo" to follow convention

### PR DESCRIPTION
**Pull request by SorenHolstHansen**
# Pull Request

## What does this PR do?
Fixes #302 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Hey @SorenHolstHansen thanks a lot for this fix :)

**Comment by SorenHolstHansen** [comment]
The failing tests don't seem to have anything to do with the change

**Comment by bidoubiwa** [comment]
@SorenHolstHansen 
No ! They are failing because the SDK is not up to date with the latest Meilisearch version :) 

I'm merging!

**Review by bidoubiwa — APPROVED** [review]
LGTM 🙏

**Pull request merged**
