### PR TITLE
Refactorise the errors

### PR DESCRIPTION
**Pull request by irevoire**
- Merge the two meilisearch error types
- Use Deserialize and Serialize to generate the string associated with every error instead of writing it by hand

### CODE REVIEW

**Review by Kerollmops — APPROVED** [review]
Looks very good to me. Implementing serde on error highly reduced the amount of code to maintain, that's nice!

**Comment by curquiza** [comment]
@irevoire is it breaking for the users?

**Comment by irevoire** [comment]
Huum when the user is accessing the error contained in a task he'll get types on the error_code and error_type instead of getting everything as string.
I think that's the only change for the user

**Comment by irevoire** [comment]
I rebased on main, you can merge

**Review by brunoocasali — APPROVED** [review]

**Comment by brunoocasali** [comment]
bors merge

**Comment by brunoocasali** [comment]
> I rebased on main, you can merge

I'll release it tomorrow :)

**Pull request merged**
