### PR TITLE
Use isahc as replacement for reqwest

### PR DESCRIPTION
**Pull request by curquiza**
⚠️ Not ready to be merged

TODO:
- [x] use isahc instead of request #49 
- [x] docs modification #96 
- [x] remove tokio #81

See: https://github.com/meilisearch/meilisearch-rust/pull/49#issuecomment-726870166

### CODE REVIEW

**Comment by curquiza** [comment]
@Mubelotix! Thanks for continuing this work by removing tokio! 😁
Just the document modifications and we will ready to merge this PR 🚀

**Comment by curquiza** [comment]
Hello @Mubelotix! Thanks for this huge work!
I put you as a final reviewer (a final check to say you are still ok with what you did).
I cannot put an official approval on this PR since I'm the author, but it looks good to me 👌 

Thanks again for your work!!

**Review by Mubelotix — APPROVED** [review]
Great! Ready to be merged

**Comment by curquiza** [comment]
Awesome!!

bors merge

**Pull request merged**
