### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by Mubelotix**

### CODE REVIEW

**Comment by Mubelotix** [comment]
Hmm GitHub has not taken into account that the first commits were already merged in #81

**Comment by curquiza** [comment]
> Hmm GitHub has not taken into account that the first commits were already merged in #81

What do you mean? Is your branch up-to-date with `isahc-dev`? Maybe it needs a rebase.

**Comment by Mubelotix** [comment]
Hmmm what I did is not what I wanted to do. I had difficulties with rebasing. I am going to delete this branch and create a new clean one.

**Comment by Mubelotix** [comment]
Switched to #96

**Pull request closed without merging**
