### PR TITLE
Add missing startedAt field in EnqueuedTask

### LINKED ISSUE #462: Tasks in state Processing do not have startedAt time
I'm unable to get `startedAt` time for current processing tasks.
```
Processing {
    content: EnqueuedTask {
        enqueued_at: 2023-04-27 1:26:02.3257223 +00:00:00,
        index_uid: Some(
            "books",
        ),
        update_type: DocumentAdditionOrUpdate {
            details: Some(
                DocumentAdditionOrUpdate {
                    indexed_documents: None,
                    received_documents: 2000,
                },
            ),
        },
        uid: 6160,
    },
}
```
But the API has this field.

### PR DESCRIPTION
**Pull request by sebastiantoh**
# Pull Request

## Related issue
Fixes #462

## What does this PR do?
Add missing startedAt field in EnqueuedTask

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Review by bidoubiwa — COMMENTED** [review]
thanks a lot for this contribution 🙏

**Comment by bidoubiwa** [comment]
Could you give a look at the failing tests?

**Comment by bidoubiwa** [comment]
Hey @sebastiantoh 

I'll be reviewing this very soon :) Thanks a lot 🙏

**Review by irevoire — APPROVED** [review]
code-wise it seems good.
I don’t have the time to test it though

**Review by curquiza — APPROVED** [review]
bors merge

**Pull request merged**
