### PR TITLE
Replace struct Query with SearchQuery

### LINKED ISSUE #332: Change name of Query struct to SearchQuery
Currently when making a search request the user has to create a `Query` structure. Nonetheless, the naming is not very clear as it could be a query on `get_indexes` or any other routes that returns multiple resources.

To make it more understandable, the `Query` structure should be renamed `SearchQuery`

### PR DESCRIPTION
**Pull request by vishalsodani**
# Pull Request

## What does this PR do?
Fixes #332 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Hey @vishalsodani thanks a lot for your contribution! 

It seems good to me :) Out of curiosity are you participating in the incoming hacktoberfest?

**Review by bidoubiwa — APPROVED** [review]
bors merge

**Comment by vishalsodani** [comment]
> Hey @vishalsodani thanks a lot for your contribution!
> 
> It seems good to me :) Out of curiosity are you participating in the incoming hacktoberfest?

Hi,

I am not sure. Maybe, I will.

**Comment by vishalsodani** [comment]
> Hey @vishalsodani thanks a lot for your contribution!
> 
> It seems good to me :) Out of curiosity are you participating in the incoming hacktoberfest?

Hi, I have decided to go for hacktoberfest. :)

**Comment by bidoubiwa** [comment]
Not sure it is backward compatible for digital ocean. If you were I would have waited the merge after the 1 October :(
But if you would like to receive a small gift from Meilisearch too, fill [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Comment by vishalsodani** [comment]
> Not sure it is backward compatible for digital ocean. If you were I would have waited the merge after the 1 October :( But if you would like to receive a small gift from Meilisearch too, fill [this form](https://meilisearch.typeform.com/to/idt5qugY).

Unfortunately, not backward compatible. 

But, I am happy to have contributed. I have filled the form; looking forward to my goodies.

**Pull request merged**
