### PR TITLE
Fix code samples

### PR DESCRIPTION
**Pull request by curquiza**

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
`search_parameter_guide_matches_1:` should have `winter feast` as filter and no `.with_attributes_to_highlight()`

**Comment by alallema** [comment]
> `search_parameter_guide_matches_1:` should have `winter feast` as filter and no `.with_attributes_to_highlight()`

I was wrong there is no more `filter` or `attribute_to_highlight` and it is the query that changes for `winter feast`

**Comment by curquiza** [comment]
@alallema done!
thanks for your review

**Review by alallema — COMMENTED** [review]
LGTM!

**Pull request merged**
