### PR TITLE
Make primary key optional

### PR DESCRIPTION
**Pull request by phdavis1027**
# Pull Request

## What does this PR do?
Fixes ##296
It's pretty straightforward! Considered passing an Option but it seemed cleaner to leave the signature of both affected functions untouched.

## PR checklist
Please check if your PR fulfills the following requirements:
- [✓] Does this PR fix an existing issue?
- [✓] Have you read the contributing guidelines?
- [✓] Have you made sure that the title is accurate and descriptive of the changes?

### CODE REVIEW

**Comment by phdavis1027** [comment]
That's odd; I would've sworn this passed ```cargo test``` locally. Will investigate.

**Comment by phdavis1027** [comment]
Sorry I haven't been able to dig deep into this in the last few days. Just to record what I have found: I can confirm that the tests pass when running a Meilisearch instance on localhost and executing ```cargo test``` from another Bash session. However, they fail when running the tests through ```docker-compose```. However, the same is actually true when testing the code from the main branch: ```cargo test``` good,  ```docker-compose``` bad.

**Comment by brunoocasali** [comment]
@phdavis1027 I think your branch is failing only in the CI because this package only supports Meilisearch v0.27. And the CI is trying to run it against the v0.28.

@bidoubiwa is working on updating this package to the latest version here https://github.com/meilisearch/meilisearch-rust/pull/297 :)

**Comment by phdavis1027** [comment]
> @phdavis1027 I think your branch is failing only in the CI because this package only supports Meilisearch v0.27. And the CI is trying to run it against the v0.28.
> 
> @bidoubiwa is working on updating this package to the latest version here #297 :)

Cool! If there's nothing else I have to do on this front, best of luck on the update!

**Comment by bidoubiwa** [comment]
Hey @phdavis1027 

With the code adapted to be compatible with v0.28, the primary key is now optional! 

Thanks a lot for pointing this out :) Unfortunately, I have to close this PR as it is already fixed on main.

Nonetheless, thanks so much for your contribution

**Pull request closed without merging**
