### PR TITLE
Add total field to get-tasks route

### LINKED ISSUE #504: [v1.3] Total Tasks in task route
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/280

----

### New implementation

Related to:
- spec: https://github.com/meilisearch/specifications/pull/253

Returns the total number of tasks matching the filters on the `GET /tasks` route.

Ensure the SDKs can handle the new get tasks response field `total`

TODO:
- [ ] Handle the response of the `getTasks` method by including the new attribute `total`

### PR DESCRIPTION
**Pull request by hmacr**
# Pull Request

## Related issue
Fixes #504 

## What does this PR do?
- Adds `total` field to `get-tasks` route

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by hmacr** [comment]
Regarding unit tests, since other tests enqueue tasks, the total returned from the API will be different each time. Adding a `>=0` assertion seemed counter-intuitive since `total` will default to `0` as it is an unsigned int.
I was thinking of calling the `delete-tasks` API before running this test, but it may not work since the test runs are concurrent. Please let me know if any unit test can be added for this. Thanks!

**Review by Kerollmops — APPROVED** [review]
That's simple and perfect 👌 Thank you!
I'll let @irevoire merge this!

**Review by irevoire — APPROVED** [review]
bors merge

**Comment by curquiza** [comment]
bors merge

**Comment by curquiza** [comment]
bors merge

**Pull request closed without merging**
