### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mk1107**
Issue #181 

I have done changes in readme.md. Please once review it.

### CODE REVIEW

**Comment by curquiza** [comment]
Oh yes, I forgot the README of this repo is specific.
Could you also update the README.tpl?
Check out this section that explains how to update the README: https://github.com/meilisearch/meilisearch-rust/blob/main/CONTRIBUTING.md#update-the-readme-

**Comment by mk1107** [comment]
> Just follow the steps in the CONTRIBUTING.md: https://github.com/meilisearch/meilisearch-rust/blob/main/CONTRIBUTING.md#update-the-readme- You always need to read the CONTRIBUTING.md file when starting an opensource PR in a repository.

I read that there It is saying update src/lib.rs or README.tpl but in README.tpl I am unable to get where to do changes so I did changes in src/lib.rs then run the commands as given but nothing happend

**Comment by mk1107** [comment]
> Push the changes you did in README.tpl and src/lib.rs then!

Done please once check

**Comment by mk1107** [comment]
Can you please add hacktoberfest accepted

**Pull request merged**
