### PR TITLE
Update version for the next release (v0.18.1)

### PR DESCRIPTION
**Pull request by bidoubiwa**
Update version of the crate to v0.18..1

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
The `getting_started` in the `code-sample` ☺️

**Comment by bidoubiwa** [comment]
It is changed in the getting started i think and in the code-samples there is not the patch version

**Review by alallema — APPROVED** [review]
LGTM! 🎉

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
