### PR TITLE
Uses big_S to cleanup tests

### LINKED ISSUE #388: Remove the need of writing to_string() everywhere in the tests by using `big_s`
Currently, throughout the tests we are adding `to_string()` everywhere. Which is tedious and reduces readability.

To clean the code, we should use the crate [`big_s`](https://docs.rs/big_s/latest/big_s/index.html)

## Todo

- Add `big_s` to the repo as a dev dependencies `cargo add big_s --dev`
- Import the library in every tests mod that needs it:
   ```rust
  mod tests {
    use big_s::S;
    //...
   ```

- Change all occurrences of for example `"something".to_string()` to `S("something")

### PR DESCRIPTION
**Pull request by romilpunetha**
# Pull Request

## Related issue
Fixes #388

## What does this PR do?
- Adds big_S crate as a dev dependency to be used for tests

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by romilpunetha** [comment]
> Hey @romilpunetha ! Thanks for you contribution :)
> 
> There are still `to_string` left in some tests. Ex line 1149 in client.rs

I focused on free strings as directed by the library documentation. Thanks for pointing this out. I found a couple more appearances and have removed them as well.

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥🔥🔥

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
