### PR TITLE
Use reqwest by default

### PR DESCRIPTION
**Pull request by irevoire**
# Pull Request

## Related issue
Fixes https://github.com/meilisearch/meilisearch-rust/issues/530 because we won’t depend on curl anymore

## What does this PR do?
- Get rid of `isahc` by default in favor of `reqwest`, which is way more used in the ecosystem

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Create an example changing the default HTTP client
- [x] Simplify the `HttpClient` trait to only require one method to be implemented
- [x] Stores a basic `reqwest::Client` in the `meilisearch_sdk::Client` instead of re-creating it from scratch for every request
- [x] Double check it works with wasm
- [x] Remove all the unwraps in `request`
- [x] Do not use the `User-Agent` when in wasm as it is often blocked by the browser

### CODE REVIEW

**Comment by gibbz00** [comment]
It is as if https://github.com/meilisearch/meilisearch-rust/pull/524 doesn't exist

**Comment by irevoire** [comment]
I did look at it, but I don't have much time to work on this. There are 4 PRs doing pretty much the same thing, and I found your trait to be more complex than the one I initially wanted sorry

**Review by irevoire — COMMENTED** [review]
bors merge

**Review by curquiza — APPROVED** [review]

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
