### PR TITLE
Settings improvements

### PR DESCRIPTION
**Pull request by Mubelotix**
Add more flexibility to the `Settings` struct and to individual methods of the `Index` struct related to settings.

### CODE REVIEW

**Comment by curquiza** [comment]
We will merge #46 and #40 before if you are ok with that! 😉

**Comment by Mubelotix** [comment]
> We will merge #46 and #40 before if you are ok with that! wink

Ok, I will update the sample file with the breaking changes in this PR.

**Comment by curquiza** [comment]
@Mubelotix. we finally merged #46 and #40! There is now a small git conflict so you need to [rebase your branch](https://gist.github.com/curquiza/5f7ce615f85331f083cd467fc4e19398) to fix it 🙂
Then I will ask someone from the core-team as a reviewer!
Thanks again for this PR, this is huge!

**Comment by curquiza** [comment]
Hello @Mubelotix, is this PR an abandoned PR or do you still plan to continue it? 😄 (no rush, just a question)

**Comment by Mubelotix** [comment]
It will be done right after the other PRs.

**Comment by Mubelotix** [comment]
I had a better idea for #38. I will start a new PR.

**Comment by Mubelotix** [comment]
Better implementation in #112.

**Pull request closed without merging**
