### PR TITLE
Checks that all error messages are correctly parsed

### LINKED ISSUE #162: Add tests for errors
Following this issue: https://github.com/meilisearch/meilisearch-rust/issues/159

Add tests to ensure that errors are parsed successfully

### PR DESCRIPTION
**Pull request by romilpunetha**
# Pull Request

## Related issue
Fixes #162

## What does this PR do?
- Adds parsing checks for the remaining two errors,ie, `InvalidTenantToken` and `Yaup`.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by romilpunetha** [comment]
@bidoubiwa I Need a review on this one as well.

**Review by bidoubiwa — APPROVED** [review]
Thanks a lot for your contributiion 🔥 LGTM 🔥

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
